In [1]:
import pandas as pd
import numpy as np

https://www.kaggle.com/code/gauravduttakiit/regression-multi-models-approach/notebook

In [22]:
train_data_all =  pd.read_csv('../data/train.csv')
train_data_all.drop('Unnamed: 0', axis=1, inplace=True)
train_data_all['day'] = pd.to_datetime(train_data_all['datetime']).dt.dayofyear
train_data_all['hour'] = pd.to_datetime(train_data_all['datetime']).dt.hour
train_data_all['year'] = pd.to_datetime(train_data_all['datetime']).dt.year
train_data_all.drop(['datetime'], axis=1, inplace=True)


train_data_all = train_data_all.drop(['registered','casual'], axis=1)

train_data_all_X = train_data_all.drop('count', axis = 1)
train_data_all_y = train_data_all['count']




test_data_all =  pd.read_csv('../data/test.csv')
test_data_all.drop('Unnamed: 0', axis=1, inplace=True)
test_data_all['day'] = pd.to_datetime(test_data_all['datetime']).dt.dayofyear
test_data_all['hour'] = pd.to_datetime(test_data_all['datetime']).dt.hour
test_data_all['year'] = pd.to_datetime(test_data_all['datetime']).dt.year
test_data_all.drop(['datetime'], axis=1, inplace=True)


test_data_all = test_data_all.drop(['registered','casual'], axis=1)

test_data_all_X = test_data_all.drop('count', axis = 1)
test_data_all_y = test_data_all['count']

In [23]:
train_data_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9063 entries, 0 to 9062
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      9063 non-null   int64
 1   holiday     9063 non-null   int64
 2   workingday  9063 non-null   int64
 3   weather     9063 non-null   int64
 4   temp        9063 non-null   float64
 5   atemp       9063 non-null   float64
 6   humidity    9063 non-null   int64
 7   windspeed   9063 non-null   float64
 8   count       9063 non-null   int64
 9   day         9063 non-null   int64
 10  hour        9063 non-null   int64
 11  year        9063 non-null   int64
dtypes: float64(3), int64(9)
memory usage: 849.8 KB

In [24]:
# import the regression module
from pycaret.regression import *

# initialize setup
s = setup(data = train_data_all, test_data = test_data_all, target = 'count', fold_strategy = 'timeseries', fold = 3, transform_target = True, session_id = 123)

In [26]:
best = create_model('et')

In [27]:
print(best)

PowerTransformedTargetRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                                max_depth=None, max_features='auto',
                                max_leaf_nodes=None, max_samples=None,
                                min_impurity_decrease=0.0,
                                min_impurity_split=None, min_samples_leaf=1,
                                min_samples_split=2,
                                min_weight_fraction_leaf=0.0, n_estimators=100,
                                n_jobs=-1, oob_score=False,
                                power_transformer_method='box-cox',
                                powe...
                                regressor=ExtraTreesRegressor(bootstrap=False,
                                                              ccp_alpha=0.0,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              max_samples=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split=None,
                                                              min_samples_leaf=1,
                                                              min_samples_split=2,
                                                              min_weight_fraction_leaf=0.0,
                                                              n_estimators=100,
                                                              n_jobs=-1,
                                                              oob_score=False,
                                                              random_state=123,
                                                              verbose=0,
                                                              warm_start=False),
                                verbose=0, warm_start=False)

In [28]:
tuned_best = tune_model(best)

In [29]:
tuned_best

PowerTransformedTargetRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                                max_depth=11, max_features='sqrt',
                                max_leaf_nodes=None, max_samples=None,
                                min_impurity_decrease=0.0002,
                                min_impurity_split=None, min_samples_leaf=5,
                                min_samples_split=7,
                                min_weight_fraction_leaf=0.0, n_estimators=200,
                                n_jobs=-1, oob_score=False,
                                power_transformer_method='box-cox',
                                pow...
                                regressor=ExtraTreesRegressor(bootstrap=False,
                                                              ccp_alpha=0.0,
                                                              criterion='mse',
                                                              max_depth=11,
                                                              max_features='sqrt',
                                                              max_leaf_nodes=None,
                                                              max_samples=None,
                                                              min_impurity_decrease=0.0002,
                                                              min_impurity_split=None,
                                                              min_samples_leaf=5,
                                                              min_samples_split=7,
                                                              min_weight_fraction_leaf=0.0,
                                                              n_estimators=200,
                                                              n_jobs=-1,
                                                              oob_score=False,
                                                              random_state=123,
                                                              verbose=0,
                                                              warm_start=False),
                                verbose=0, warm_start=False)

In [30]:
tuned_best.__dict__

{'regressor': ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                     max_depth=11, max_features='sqrt', max_leaf_nodes=None,
                     max_samples=None, min_impurity_decrease=0.0002,
                     min_impurity_split=None, min_samples_leaf=5,
                     min_samples_split=7, min_weight_fraction_leaf=0.0,
                     n_estimators=200, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False),
 'power_transformer_method': 'box-cox',
 'power_transformer_standardize': True,
 'transformer': PowerTransformer(copy=True, method='box-cox', standardize=True),
 'func': None,
 'inverse_func': None,
 'check_inverse': False,
 '_fit_vars': set(),
 '_training_dim': 1,
 'transformer_': PowerTransformer(copy=True, method='box-cox', standardize=True),
 'regressor_': ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                     max_depth=11, max_features='sqrt', max_leaf_nodes=None,
                     max_samples=None, min_impurity_decrease=0.0002,
                     min_impurity_split=None, min_samples_leaf=5,
                     min_samples_split=7, min_weight_fraction_leaf=0.0,
                     n_estimators=200, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)}

In [ ]:
# To save the model with pickle file 
# save_model(best,'lightgbm-location-velo')
# Tuned_rf = tune_model(rf) 
# Tuned_rf